# Generated by Django 4.2.6 on 2023-11-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ficheros', '0002_auto_creador_moto_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='motos_photos/'),
        ),
    ]
