# Generated by Django 4.2.6 on 2023-11-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ficheros', '0003_moto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
